mini_twitter/mini_twitter/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import consult_gpt.consult

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('message/', include('message.urls')),
    path('comment/', include('comment.urls')),
    path('chat_with_gpt/', consult_gpt.consult.chat_with_gpt, name='chat_with_gpt'),
    path('consult/', consult_gpt.consult.consult, name='consult'),
    path('', include('posts.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mini_twitter/posts/urls.py
from django.urls import path

from .views import PostListView, PostCreateView, PostDetailView, \
    like, PostUpdateView, PostDeleteView, LikedPostUserList, PostUserListView

urlpatterns = [
    path('', PostListView.as_view(), name='posts_list'),
    path('posts_list/<str:folder>', PostListView.as_view(), name='posts_list'),
    path('like/<int:pk>', like, name='like'),
    path('liked_post_user/<int:pk>', LikedPostUserList.as_view(), name='liked_post_user'),
    path('posts_list_user/<int:user_id>', PostUserListView.as_view(), name='posts_list_user'),
    path('create-post/', PostCreateView.as_view(), name='create_post'),
    path('update-post/<int:pk>', PostUpdateView.as_view(), name='post_update'),
    path('delete-post/<int:pk>', PostDeleteView.as_view(), name='post_delete'),
    path('post-detail/<int:pk>', PostDetailView.as_view(), name='post_detail'),


]

mini_twitter/message/models.py
from django.db import models
from django.urls import reverse
from users.models import User


class Message(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sent_messages')
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='received_messages')
    title = models.CharField(max_length=128, blank=True, null=False)
    text = models.TextField(blank=True, null=False)
    created_at = models.DateTimeField(auto_now_add=True)
    unread = models.BooleanField(default=True)

    def get_absolute_url(self):
        return reverse('message_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return f'{self.title} {self.text}'

mini_twitter/posts/models.py
from django.db import models
from django.urls import reverse
from users.models import User
from django_resized import ResizedImageField


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=256)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    like = models.ManyToManyField(User, blank=True, related_name='liked_post')
    image = ResizedImageField(size=[600, 400], upload_to='posts/image', blank=True, null=True)

    def __str__(self):
        return f'Post: {self.title}, created: {self.created_at}'

    def get_absolute_url(self):
        return reverse('post_detail', kwargs={'pk': self.pk})

mini_twitter/posts/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'image', 'content']
        widgets = {
            'image': forms.FileInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control'}),
        }

mini_twitter/posts/views.py
from comment.models import Comment
from django.db.models import Count
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, UpdateView
from django.views.generic.edit import DeleteView

from .forms import PostForm
from .models import Post


# def posts_list(request, user_id=None):
#     comment_count = dict()
#     if user_id:
#         posts = Post.objects.filter(user__id=user_id)
#     else:
#         posts = Post.objects.all()
#     if posts:
#         for post in posts:
#             comment_count[str(post.pk)] = Comment.objects.filter(post__id=post.pk).count()
#     return render(request, 'posts/posts_list.html', {'posts': posts, 'comment_count': comment_count})

# перевірка чи запит було здійснено з нашого домену!
def is_valid_request(request):
    allowed_origin = "http://127.0.0.1"
    origin = request.headers.get("Origin") or request.headers.get("Referer")
    if origin.startswith(allowed_origin):
        return True
    return False


class PostListView(ListView):
    model = Post
    template_name = 'posts/posts_list.html'
    context_object_name = 'posts'
    paginate_by = 5

    def get_queryset(self):
        if self.kwargs.get('folder'):
            folder = self.kwargs.get('folder')
            if folder == 'my':
                posts = Post.objects.filter(user=self.request.user).select_related('user')
            elif folder == 'follow':
                follow_users = self.request.user.following.all()
                posts = Post.objects.filter(user__in=follow_users).select_related('user')
        else:
            posts = Post.objects.all().select_related('user')
        return posts.annotate(comment_count=Count('comment', distinct=True),
                              like_count=Count('like', distinct=True)).order_by('-created_at')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.kwargs.get('folder'):
            context['folder'] = self.kwargs['folder']
        else:
            context['folder'] = 'all'

        return context


class PostUserListView(ListView):
    model = Post
    template_name = 'posts/posts_list.html'
    context_object_name = 'posts'
    paginate_by = 2

    def get_queryset(self):
        posts = Post.objects.filter(user__id=self.kwargs['user_id']).select_related('user')
        return posts.annotate(comment_count=Count('comment', distinct=True),
                              like_count=Count('like', distinct=True)).order_by('-created_at')

    # def get_context_data(self, *, object_list=None, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     user = self.request.user
    #     follow_users = user.following.all()
    #     context['posts'] = context['posts'].filter(user__in=follow_users).select_related('user').annotate(
    #         comment_count=Count('comment', distinct=True),
    #         like_count=Count('like', distinct=True)).order_by('-created_at')
    #     return context


# def get_context_data(self, *, object_list=None, **kwargs):
#     context = super().get_context_data(**kwargs)
#     comment_count = dict()
#     if context['posts']:
#         comment_count = Comment.objects.values('id')
#     context['comment_count'] = comment_count
#     return context


# def comments_list(request, post_id):
#     comments = Comment.objects.filter(post__id=post_id)
#     post = get_object_or_404(Post, pk=post_id)
#     context = {
#         'comments': comments,
#         'post': post
#     }
#     return render(request, 'posts/comments_list.html', context)


# def create_post(request):
#     if request.method == 'POST':
#         form = PostForm(request.POST, request.FILES)
#         if form.is_valid():
#             post = form.save()
#             return redirect('post_detail', post_id=post.pk)
#     else:
#         form = PostForm()
#     return render(request, 'posts/create_post.html', {'form': form})

class PostCreateView(CreateView):
    form_class = PostForm
    template_name = 'posts/create_post.html'

    def form_valid(self, form):
        if is_valid_request(self.request):
            form.instance.user = self.request.user  # Передаємо користувача
            return super().form_valid(form)
        else:
            return HttpResponse(f"Go to Hell")


# def post_detail(request, post_id):
#     post = get_object_or_404(Post, pk=post_id)
#     comments = Comment.objects.filter(post__id=post_id)
#     context = {"post": post, 'count_comments': len(comments), 'comments': comments}
#     return render(request, "posts/post_detail.html", context)

class PostDetailView(DetailView):
    model = Post
    template_name = 'posts/post_detail.html'

    def get_queryset(self):
        post = super().get_queryset()
        return post.select_related('user').annotate(comment_count=Count('comment', distinct=True),
                                                    like_count=Count('like', distinct=True))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comments'] = Comment.objects.filter(post__id=self.kwargs['pk']).select_related('user').order_by(
            '-created_at')
        return context


class PostUpdateView(UpdateView):
    template_name = 'posts/post_update.html'
    model = Post
    fields = ["title", "image", "content"]

    def get_queryset(self):
        return super().get_queryset().select_related('user')


class PostDeleteView(DeleteView):
    model = Post
    success_url = reverse_lazy('posts_list')
    template_name = 'posts/post_delete.html'


# def create_comment(request):
#     if request.method == 'POST':
#        form = CommentForm(request.POST, request.FILES)
#        if form.is_valid():
#             comment = form.save()
#             return redirect('comment_detail', comment_id=comment.pk)
#     else:
#         form = CommentForm()
#     return render(request, 'posts/create_comment.html', {'form': form})


def like(request, pk):
    post = Post.objects.get(pk=pk)
    post.like.add(request.user)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


class LikedPostUserList(ListView):
    model = Post
    template_name = 'posts/liked_post_user.html'
    context_object_name = 'post_liked_user'

    def get_queryset(self):
        post_liked_user = Post.objects.get(pk=self.kwargs['pk']).like.all()
        return post_liked_user

mini_twitter/posts/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Security-Policy" content="default-src 'self';
                                                        script-src 'self' 'unsafe-inline' 'unsafe-eval' cdn.jsdelivr.net code.jquery.com;
                                                        style-src 'self' 'unsafe-inline' cdn.jsdelivr.net;
                                                        img-src 'self' data: localhost;"
                                                        report-to="csp-endpoint">

    <title>Mini Twitter</title>

    <!-- Add Bootstrap CSS link -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="{% static '/js/bootstrap.min.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <style>
        .unread {
            background-color: #808080; /* Змініть колір фону на ваш смак */
            font-weight: bold; /* Змініть стиль шрифту на ваш смак */
            }
        /* You can still use custom CSS styles here if needed */
    </style>
</head>
<body>
<header class="bg-primary text-white py-4">
    <div class="container">
        <h1 class="display-3">Mini Twitter</h1>
        <nav class="d-flex justify-content-between align-items-center">
            <ul class="nav">
                <li class="nav-item">
                    <a class="nav-link text-white" href="{% url 'posts_list' %}"> Усі пости</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link text-white" href="{% url 'users_list' %}">Користувачі</a>
                </li>
                <a href="{% url 'create_post' %}" class="btn btn-success">Створити пост</a>
                <a href="{% url 'consult' %}" class="btn btn-success">Запитати у консультанта</a>

            </ul>
            <div class="ms-auto">
                    <span class="me-3 text-white">Вітаю, <a href="{% url 'user_detail' user.pk %}"
                                                            class="btn btn-outline-info my-2 my-sm-0">{{ user.username }}</a>
                    <a href="{% url 'logout' %}" class="btn btn-outline-info my-2 my-sm-0">Вийти</a>
                    </span>
            </div>
            {% else %}
            </ul>
            <div class="ms-auto">
                <span class="me-3 text-white">Вітаю
                    <a href="{% url 'login' %}" class="btn btn-outline-info my-2 my-sm-0 me-2">Увійти</a>
                    <a href="{% url 'register' %}" class="btn btn-outline-info my-2 my-sm-0">Зареєструватися</a>
                </span>
            </div>
            {% endif %}


        </nav>
    </div>
</header>


<div class="container my-5">
    <div class="row">
        <!-- Ліва бічна панель -->
        <nav id="sidebar" class="col-md-3 col-lg-2 d-md-block bg-light sidebar">
            <div class="position-sticky">
                <ul class="nav flex-column">
                    <!-- Відображення логотипу користувача, якщо він авторизований -->
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <img src="{{ user.profile.avatar.url }}" alt="Аватар користувача"
                             class="img-fluid rounded-circle">
                        <h4>{{ user.username }}</h4>
                    </li>
                    {% load custom_filters %}
                    <li class="nav-item">
                        {% with count=user|unread_message_count %}
                        {% if count%}
                        <strong>
                            <a class="nav-link" href="{% url 'message_list' 'inbox' %}">Повідомлення
                                ({{count}})</a>
                        </strong>
                        {% else %}
                        <a class="nav-link" href="{% url 'message_list' 'inbox' %}">Повідомлення</a>
                        {% endif %}
                        {% endwith %}
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'change_user_info' user.pk %}">Редагувати профіль</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'change_profile' user.profile.pk %}">Редагувати Аватар та
                            Біо</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'posts_list' 'my' %}">Мої пости</a>
                    </li>

                    {% endif %}
                    <!-- Додайте інші пункти меню сюди -->
                </ul>
            </div>
        </nav>

        <!-- Основний блок контенту (посередині) з вирівнюванням по верхньому краю -->
        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4 align-items-start">
            {% block content %}{% endblock %}
        </main>
    </div>
</div>

<footer class="bg-primary text-white text-center py-3">
    <div class="container">
        <p>&copy; 2023 Mini Twitter</p>
    </div>
</footer>

<!-- Add Bootstrap JS scripts at the end of the body if needed -->

</body>
</html>

mini_twitter/posts/templates/consult.html
{% extends "base.html" %}
{% block content %}
<div class="container mt-5">
    <h1 class="mb-4">Запитати у консультанта</h1>
    <form id="chat-form" class="mb-4">
        <div class="input-group">
            <input type="text" id="user-input" placeholder="Введіть ваше питання..." class="form-content">
            <div class="input-group-append">
                <button type="submit" class="btn btn-primary">Надіслати</button>
            </div>
        </div>
    </form>

    <div id="loading-spinner" class="spinner-border text-primary mb-3" role="status">
        <span class="sr-only">Завантаження...</span>
    </div>

    <div id="chat-response" class="border p-3">

    </div>

    <script>
        $("#chat-form").submit(function(e) {
            e.preventDefault();

            $("#loading-spinner").show();

            let userInput = $("#user-input").val();
            $.get("/chat_with_gpt/", { user_input: userInput }, function(data) {
                $("#loading-spinner").hide()

                $("#chat-response").text("Консультант: " + data.response);
                $("#user-input").val('');
            });
        });
    </script>
</div>

{% endblock %}

mini_twitter/posts/templates/pagination.html
<nav aria-label="Page navigation example">
    <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">&laquo;</a>
        </li>
        {% endif %}
        {% for i in page_obj.paginator.page_range %}
            {% if page_obj.number == i %}
                <li class="page-item active"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">&raquo;</a>
        </li>
        {% endif %}
    </ul>
</nav>